### PR TITLE
 Improved: SI WFE interpolation

### PR DESCRIPTION
**Pull request by robelgeda**
Improved version of PR #174.  Zernike values are interpolated using `scipy.interpolate.griddata`'s cubic method. This gives the best approximations and adds smallest overhead.

### CODE REVIEW

**Comment by mperrin** [comment]
I'm confused - what is improved in this versus #174? Looks identical to me.

**Comment by mperrin** [comment]
Is the only difference the call to `np.isnan()` for checking for invalid interpolation outputs and then using the nearest neighbor instead?

**Comment by robelgeda** [comment]
Yes, also the range for the Zernike for loop should be 1->37 instead of 1->36.

**Comment by robelgeda** [comment]
@mperrin I fixed the conflict. At this point the only difference is the `for` loop range.

**Comment by mperrin** [comment]
OK, it looks like the actual code tests are fine for this; the Travis build is failing because of the docs issue (#193), not because of this change. So I'm going to go ahead and merge it. 

@robelgeda, any chance you might be able to try to dig into the docs build problems (for webbpsf and poppy both) over the next few days sometime? See #193.

**Pull request merged**
