### PR TITLE
WFIRST Cycle 7 Updates

### PR DESCRIPTION
**Pull request by robelgeda**
This is the final draft of WFIRST Cycle 7 updates. The  Following changes have been made:

webbpsf:
-  Edits to pupil file names.
- Edits to Zernike file name.

webbpsf-data-source:
- New filter: `WFI/filters/R062_throughput.fits`.
- Edit: `WFI/filters.tsv` to add R062.
- Updated Zernike Coefficients: `WFI/wim_zernikes_cycle7.csv`.
- Updated Pupils:  `WFIRST_SRR_WFC_Pupil_Mask_Longwave_2048.fits` and `WFIRST_SRR_WFC_Pupil_Mask_Shortwave_2048.fits`.
- Old Zernike Coeff moved to: `WFI/sources/cycle6/WFI/wim_zernikes_cycle6.csv`
- Old Pupils moved to: `_Obsolete/cycle6_pupils/.`.
- Data generation material stored in `WFI/sources/cycle7`.

### CODE REVIEW

**Comment by mperrin** [comment]
Can you explain a bit more about the pupil updates? What were you able to figure out about the coordinate system conventions?

**Comment by robelgeda** [comment]
Sure, I was able to obtain the instrument layout in both cycles. Both indicate that the coordinate system is `Payload FOV {X, Y}`. See axis labels below: 

screen shot 2017-11-08 at 6 00 32 pm

I was able to figure out that the WSM rotated 90 degrees as follows.

screen shot 2017-11-08 at 6 39 51 pm
Where purple and orange arrows point to the origin in cycle 6 and 7 respectively.


After that I checked if the pupil files do the same transformation. 
screen shot 2017-11-08 at 10 34 31 pm

I found this to be evidence that the pupil coordinate system conventions are the same.

**Comment by robelgeda** [comment]
Also, the people at Goddard shared a script to convert the pupil from tiffs to fits. One thing to note is that I had to flip the image upside down before converting it to fits format because the y axis of a fits file starts to index at the top left.

**Comment by robelgeda** [comment]
I tested the changes using the example Jupyter netbooks and the /webbpsf/tests/test_wfits.py script. Everything seems to be in order.

**Pull request closed without merging**
