### PR TITLE
Adding distortion to PSFs

### PR DESCRIPTION
**Pull request by shanosborne**
This will automatically make calc_psf() produce a 4 extension PSF: over-sampled, detector-sampled, over-sampled and distorted, and detector-sampled and distorted. 

This will be the default state, but it can be turned off with the keyword argument add_distortion=False. NIRCam, NIRISS, and FGS also have the keyword crop_psf=True which will make the distorted and un-distorted PSFs be the same size (this is always true for the other instruments). 

This closes issue #192

### CODE REVIEW

**Comment by shanosborne** [comment]
How do we include a download of pysiaf in webbpsf? I realize that I'm not sure how do this

**Comment by mperrin** [comment]
Then let’s plan for 2

**Comment by mperrin** [comment]
Looks like a couple of the test functions are failing. You’ll want to try running those functions locally to try debugging them.

**Comment by mperrin** [comment]
@JarronL if you've got the time, you might be interested in taking a look at this PR. @shanosborne has implemented geometric distortions of PSFs based on the SIAF distortion coefficients. 

I'm mentioning this to you both because I expect you might be interested in using this in pyNRC, and also more generally because it would be nice to have feedback on the tutorial notebook from someone on one of the instrument teams. Please let Shannon and me know if anything's unclear in that tutorial or if you can think of any questions you'd like answered in it. Thanks.

**Comment by JarronL** [comment]
I was actually looking at this over the weekend. Could you clarify how these distortions relate to information inside si_zernikes_isim_cv3.fits, which we use apply WFE variations to the PSF shape? Are these things mutually exclusive or would you use both when generating a location-specific PSF?

**Comment by JarronL** [comment]
Thinking about this a little more, I'm still unsure if applying these distortions to the PSF makes sense. For instance, if I have an off-axis point source at some sky location, the PSF certainly gets distorted, but my impression is that this should already be accounted for in the position-dependent WFE aberrations? I think the SIAF information is perhaps more useful in distorting an input image (such as positions of a star cluster) that are then convolved with the field-dependent PSF? Not exactly sure how I would handle extended sources...

**Comment by mperrin** [comment]
Not exactly. These are really orthogonal issues, and can both be applied. 

* The position-dependent WFE data (and telescope OPD files, etc) reflect changes in wavefront phase _at a given location in the pupil_. 
* The geometric distortion data reflect changes in _the apparent locations of each given location_. 

I find this easier to understand with a concrete example. HST ACS has fairly large distortion, larger than the other HST instruments. This can easily be seen in PSFs, for instance figures 5.15 and 5.16 at http://www.stsci.edu/hst/acs/documents/handbooks/current/c05_imaging7.html#357374.  The diffraction spikes are not orthogonal in the output PSF, despite being caused by orthogonal SM supports in the HST OTA pupil. The HST PSF simulator Tiny Tim models this as a transformation of the output PSF to add the distortion, and we're trying here to include a similar treatment for JWST.

The result of geometric distortion is that detector pixels are not ideal square sections of the sky. They're skewed parallelograms.  The corresponding effect for JWST is that the PSF diffraction spikes aren't at precisely 60 degree intervals, but ever so slightly off from that.  This is a different mapping than the WFE - that affects the amplitude of speckles, this changes their apparent locations. 

Diffractively I think the more rigorous way to think about this would be as a distortion of the telescope exit pupil, so the axes of V2 and V3 aren't skew there, and so on for higher order terms.  Then that skewed distorted pupil gets Fourier transformed into a skewed PSF. But we can alternatively apply a model of this effect in the image plane too, and that's in practice easier since we have detailed image plane distortion all over the field of view but don't have the equivalent amount of measurements in pupil space.

**Comment by mperrin** [comment]
For JWST the distortions are pretty small in most cases. Largest for FGS, as can be seen in 
this figure of the focal plane: 
https://jwst-docs.stsci.edu/display/JTI/JWST+Field+of+View?preview=/32316043/32316051/JWST%20FOV.png

**Comment by JarronL** [comment]
Thanks. I think my confusion stems from the fact that I'm unclear exactly how the SI WFE extractions were performed (were these derived from weak lens observations?). Your explanation seems to make sense, especially if I think about it in terms of distortion of the field far away from a given PSF. The HST data clearly demonstrates that the PSF diffraction spikes get skewed when projected on the detector plane. This makes sense in the context of how the SI optics distorts the field. 

That being said, I'm still not sure when it's best to add distortion to a simulated observation. For a single point source, it probably doesn't matter. However, if you just distort the PSF, then that will not modify the shape of an extended source unless you have a differently distorted PSF for every pixel. Perhaps the most straightforward approach is to build an undistorted convolved image then apply rotation and image distortion? Either way, the `apply_distortion()` function seems like it will do the job.

**Comment by mperrin** [comment]
For where the SI WFE data comes from,  see the draft release notes at the URL I emailed you yesterday. There’s a link there to David Aronstein‘s ISIM optics cryotest report, both the exhaustive 200 page NGIN version and the more digestible SPIE paper. 

You’re absolutely right that distorting extended sources is more complicated than what this function does. This is just one piece of the puzzle for enabling simulating data just a tiny bit more like what will really be on the detectors...

**Comment by mperrin** [comment]
@shanosborne anything more you're planning to do on this now, or do you think it's basically ready to merge?

**Comment by shanosborne** [comment]
@mperrin I think this has everything needed for the distortion functions (and I also updated the MIRI rotation value in this pull request). The only thing is that I haven't gotten a chance to talk to you about the pupil shear values, but that could be done separately.

**Comment by mperrin** [comment]
Sure, pupil shear can be a separate PR. I'll go ahead and merge this now.

**Pull request merged**
